### ISSUE TITLE
hardcoded path :( 

### ISSUE THREAD

**Issue by huihuifan** [luheng/deep_srl#1]
I don't think you should hardcode the path (for ex: in run_end2end.sh). It becomes quite confusing to use this code in different places. In many instances, people probably either already have this set in bashrc or otherwise have a path configuration, and you are hard setting it, which can create issues.

**Comment by luheng** [comment]
Thank you for pointing this out. I wrote these scripts mainly for showing users how to run the python code. Sorry for the confusion. Will clarify.
