### ISSUE TITLE
constraints

### ISSUE THREAD

**Issue by cosmozhang** [luheng/deep_srl#10]
In the paper, you mentioned the constraints were used. In the code, where can I find them? 
Thanks!

**Comment by luheng** [comment]
Which constraints are you referring to?
The code here uses the BIO constraints, which are the only constraints included in the main results in the 2017 paper.
The code for A* search was implemented in c++ and was not integrated with the rest of the Theano code (which make it hard to run/setup, etc.).

**Comment by cosmozhang** [comment]
Thanks for your swift reply! In which file did you put BIO constraints in your code?

**Comment by luheng** [comment]
https://github.com/luheng/deep_srl/blob/master/python/neural_srl/shared/inference.py
