### ISSUE TITLE
error run_en2end.sh

### ISSUE THREAD

**Issue by im-tired-boss** [luheng/deep_srl#21]
```
Traceback (most recent call last):
  File "python/predict.py", line 161, in <module>
    args.input)
  File "python/predict.py", line 69, in get_scores
    model = BiLSTMTaggerModel(data, config=config, fast_predict=True)
  File "/home/mario/git/deep_srl/python/neural_srl/theano/tagger.py", line 66, in __init__
    self.is_train)
  File "/home/mario/git/deep_srl/python/neural_srl/theano/layer.py", line 221, in connect
    return LSTMLayer.connect(self, inputs, mask, is_train)
  File "/home/mario/git/deep_srl/python/neural_srl/theano/layer.py", line 178, in connect
    n_steps=max_length) # scan steps
  File "/home/mario/.local/lib/python2.7/site-packages/theano/scan_module/scan.py", line 1048, in scan
    local_op = scan_op.Scan(inner_inputs, new_outs, info)
  File "/home/mario/.local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 216, in __init__
    [])
  File "/home/mario/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1300, in cmodule_key_variables
    c_compiler)
  File "/home/mario/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1350, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: 'module' object has no attribute '_get_ndarray_c_version'
```

I get the error above when trying to run run_en2end.sh

**Comment by maaariogg** [comment]
got it running by installing older version of numpy

`pip uninstall numpy
pip install numpy==1.13.3`

**Comment by im-tired-boss** [comment]
got it running by installing older version of numpy

`pip install numpy==1.13.3`

**Comment by Nasidiqi** [comment]
I am receiving this error on ubuntu machine

Model building and loading duration was 0:00:28.



Running model duration was 3:24:52.
Task: srl
Allow new words in test data: True
Embedding size=100
Read 295330 sentences.
Data loading duration was 0:00:30.
Using 2 feature types, projected output dim=200.
('lstm_0_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faa7c08d110>
('lstm_1_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faa7c08d7d0>
('lstm_2_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faac68df910>
('lstm_3_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faac68df350>
('lstm_4_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faac68dfcd0>
('lstm_5_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faac68f7c50>
('lstm_6_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faac68f76d0>
('lstm_7_rdrop', 0.1, True)
<neural_srl.theano.layer.HighwayLSTMLayer object at 0x7faac68f7b90>
46989 32054
46989 2
Loaded model from: /home/ubuntu/deep_srl-master/resources/conll05_ensemble/model1.npz
Model building and loading duration was 0:00:03.


and one  model is taking about 4 hours  to run ... any idea what to doo?

**Comment by im-tired-boss** [comment]
if you're getting the same error as the one I posted on this issue. try the solution I mentioned 

`pip uninstall numpy `

`pip install numpy==1.13.3`

**Comment by Nasidiqi** [comment]
@mario-rggj 

What version of python are you using to run this model ? i am using Python 2.7.15rc1

**Comment by Nasidiqi** [comment]
@mario-rggj  hi mario, did you ever run this model on any real data set and got any results?
