### ISSUE TITLE
AssertionError in processing CONLL2012 data

### ISSUE THREAD

**Issue by celine-lee** [luheng/deep_srl#28]
Hi,

When running the pre-processing for the Ontonotes CONLL2012 data, I run into this AssertionError at line 64 of the process_conll2012.py file :
`assert tags[t][props[t]] in {"B-V", "B-I"}`
due to the if-statements at line 149. I believe it is caused by when the tag passed into the file includes a nested verb label, such as the one below, where the word is labeled as a verb and is also the first word in a continued ARG2 span.

<img width="960" alt="deep_srl_nestedcarg2v" src="https://user-images.githubusercontent.com/22714518/80153970-73dfc700-8573-11ea-9a81-6524b8b1d2a0.PNG">

Any suggestions on how to handle this?

**Comment by celine-lee** [comment]
I re-assembled the CONLL-2012 data, and these nested labels were removed, so I no longer have this issue.

**Comment by StudentWorker** [comment]
I re-assembled the CONLL-2012 data,but not sucessful.
