### ISSUE TITLE
Cannot install deep_srl

### ISSUE THREAD

**Issue by herlimenezes** [luheng/deep_srl#3]
Hello! I am involved in a doctoral research about the use of SRL in order to perform critical discourse analysis. Currently i am using an old python application, practNLPtools, which works fine, but outdated. I read your paper, and I was pleased with your idea of a Theano based SRL, which is fine, however I was unable to run your code. I have cloned the repository downloaded the necessary dependencies (as I guess). 
I have checked cloned repo, all files are there. Probably I making a mistake when configuring files, since I am working in try-error mode. Could  you give me some hints? 
Thank you in advance for your attention.

[issueSRL.txt](https://github.com/luheng/deep_srl/files/1538985/issueSRL.txt)

**Comment by luheng** [comment]
Two possible issue here:
1. Looks like you are missing the pretrained model directories conll05_propid_mode, conll05_ensemble, etc. Instructions for getting them can be found in the readme:
Decompress the models (in resources) under the neural_srl directory. For example, under the codebase directory:
tar -zxvf resources/conll05_model.tar.gz

2. If you have already decompressed the model directories, looks like there's a typo in the command:
`[herlimenezes@aries deep_srl]$ python python/interactive.py --model conll05_model/ --pidmodel conll05-propid_model`

which should be "conll05_propid_model".

Hope this helps,
