### ISSUE TITLE
About Training Data

### ISSUE THREAD

**Issue by ayyappa428** [luheng/deep_srl#9]
Hi,
can we create our own training data.?
In the code where we are giving training data?
can i look the dataset?
Here we are giving pre-trained models?
I want to add some more data to the existing data and want to train a model
please suggest me.

**Comment by luheng** [comment]
Yes, please see README for training data format.
The data used to train this model (CoNLL2005 and CoNLL2012) are under the LDC license and not publicly available.

**Comment by pluto-junzeng** [comment]
Hi
It is a wonderful work。
I hava some idea in SRL ，but not hava the dataset
Can you sent  the dataset to me by emails？
thanks
CHINA WUHAN
